### ISSUE TITLE
12-factorize the app

### ISSUE THREAD

**Issue by tracker1** [synthesis-js/react-synthesis#44]
1. Make the default config use two environment variables for those settings, so they don't have to be edited by hand.
2. Add an appropriate onbuild dockerfile
3. publish to dockerhub so it can be run more easily in a given environment

**Comment by jocnjr** [comment]
Hey Michael, thanks a lot for the input.

You're totally right. We've should and we will push a dockerfile for production and, maybe, dev environment. 

Hold on tight and we'll get back to you.

All the best,

**Comment by jocnjr** [comment]
Hey Michael, now we have a docker file for the production environment. Check it out.

>docker build -f Dockerfile-prod -t react-synthesis/backend .
>docker run -t -p 49170:3000 react-synthesis/backend

**Comment by tracker1** [comment]
Having a separate dockerfile for prod violates the concept of the same container for dev/test/prod... the key settings, or even which settings file to use should come from environment variables when running the container.

see: https://12factor.net/config

For more info on creating portable applications...  https://12factor.net/

**Comment by jocnjr** [comment]
definitely. we're using variables next time. Thanks

**Comment by tracker1** [comment]
Also, there are `-onbuild` containers for node already available which should streamline your dockerfile...

```
FROM node@6-onbuild
```

Assuming `npm start` will run the build of your app after an `npm install` ... you can have an `install` script that will run `npm run build` that does your build... this way, the onbuild will take whatever is outputted after the build, then use that inside the container... from there, having environment variables for what config to use will allow for a more streamlined deployment experience.
